In [20]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, MaxAbsScaler, RobustScaler
import numpy as np

In [21]:
df = pd.read_csv("mtcars_mod.csv")

In [22]:
df

car   mpg  cyl   disp   hp   drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110   3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110   3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93   3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110   3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0    0   3.15  3.440 -17.02   0   0   
5               Valiant  18.1    6  225.0  105   2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0    0   3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7    0   3.69  3.190 -20.00   1   0   
8              Merc 230  22.8    4  140.8    0  52.12  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123   3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123   3.92  3.440 -18.90   1   0   
11           Merc 450SE  16.4    8  275.8    0   3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  28.92  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8    0   3.07  3.780 -18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0    0   2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215   3.00  5.424 -17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230   3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7    0  38.17  2.200 -19.47   1   1   
18          Honda Civic  30.4    4   75.7    0   4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65   4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1    0   3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150   2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150   3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0    0   3.73  3.840 -15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0    0   3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0    0   4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  51.29  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1    0   3.77  1.513 -16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264   4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0    0   3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335   3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0    0  42.56  2.780 -18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [23]:
scaler_minmax = MinMaxScaler()
scaler_maxabs = MaxAbsScaler()
scaler_standard = StandardScaler()
scaler_robust = RobustScaler()

In [34]:
scaler_maxabs = MaxAbsScaler()
hp_df = df[['hp']]
scaler_maxabs.fit(hp_df)
scaler_maxabs.transform(hp_df)

array([[0.32835821],
       [0.32835821],
       [0.27761194],
       [0.32835821],
       [0.        ],
       [0.31343284],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.36716418],
       [0.36716418],
       [0.        ],
       [0.53731343],
       [0.        ],
       [0.        ],
       [0.64179104],
       [0.68656716],
       [0.        ],
       [0.        ],
       [0.19402985],
       [0.        ],
       [0.44776119],
       [0.44776119],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.27164179],
       [0.        ],
       [0.7880597 ],
       [0.        ],
       [1.        ],
       [0.        ]])

In [25]:
scaler_minmax = MinMaxScaler()
disp_df = df[["disp"]]
scaler_minmax.fit(disp_df)
scaler_minmax.transform(disp_df)

array([[-0.57975032],
       [-0.57975032],
       [-1.00602601],
       [ 0.22361542],
       [ 1.05977159],
       [-0.0469057 ],
       [ 1.05977159],
       [-0.68877852],
       [-0.73714442],
       [-0.51744848],
       [-0.51744848],
       [ 0.36953287],
       [ 0.36953287],
       [ 0.36953287],
       [ 1.97790385],
       [ 1.87953254],
       [ 1.71558035],
       [-1.24621597],
       [-1.2708088 ],
       [-1.3085178 ],
       [-0.90683494],
       [ 0.71547199],
       [ 0.60070545],
       [ 0.97779549],
       [ 1.38767597],
       [-1.24375669],
       [-0.90519541],
       [-1.11177517],
       [ 0.9859931 ],
       [-0.70271446],
       [ 0.57611263],
       [-0.89945709]])

In [37]:
scaler_robust = RobustScaler()
drat_df = df[["drat"]]
scaler_robust.fit(drat_df)
scaler_robust.transform(drat_df)

array([[ 1.88295165e-01],
       [ 1.88295165e-01],
       [ 1.37404580e-01],
       [-6.46310433e-01],
       [-5.75063613e-01],
       [-9.72010178e-01],
       [-5.13994911e-01],
       [-2.54452926e-02],
       [ 4.92671756e+01],
       [ 2.08651399e-01],
       [ 2.08651399e-01],
       [-6.56488550e-01],
       [ 2.56539440e+01],
       [-6.56488550e-01],
       [-7.98982188e-01],
       [-7.27735369e-01],
       [-4.93638677e-01],
       [ 3.50687023e+01],
       [ 1.23664122e+00],
       [ 5.13994911e-01],
       [-1.52671756e-02],
       [-9.72010178e-01],
       [-5.75063613e-01],
       [ 1.52671756e-02],
       [-6.46310433e-01],
       [ 3.71501272e-01],
       [ 4.84223919e+01],
       [ 5.59796438e-02],
       [ 5.13994911e-01],
       [-9.66921120e-02],
       [-1.78117048e-01],
       [ 3.95368957e+01]])

In [28]:
scaler_standard = StandardScaler()
wt_df = df[["wt"]]
scaler_standard.fit(wt_df)
scaler_standard.transform(wt_df)

array([[-0.62016658],
       [-0.35538219],
       [-0.93167763],
       [-0.00233633],
       [ 0.23129695],
       [ 0.25206436],
       [ 0.36628508],
       [-0.02829559],
       [-0.06983039],
       [ 0.23129695],
       [ 0.23129695],
       [ 0.88547016],
       [ 0.5324243 ],
       [ 0.58434281],
       [ 2.11074695],
       [ 2.29142336],
       [ 2.20939212],
       [-1.05628205],
       [-1.6637286 ],
       [-1.43528716],
       [-0.78111396],
       [ 0.31436657],
       [ 0.2261051 ],
       [ 0.64664502],
       [ 0.65183687],
       [-1.33145014],
       [-1.11858426],
       [-1.76964235],
       [-0.04906299],
       [-0.46441106],
       [ 0.36628508],
       [-0.45402735]])

In [38]:
from scipy.stats import yeojohnson
from sklearn.preprocessing import normalize

In [31]:
mpg_yj, mpg_lambda = yeojohnson(df['mpg'])
mpg_yj

array([2.9918174 , 2.9918174 , 3.06540468, 3.00868837, 2.888285  ,
       2.85924149, 2.65037848, 3.12619264, 3.06540468, 2.91180605,
       2.84436838, 2.77159437, 2.81903285, 2.70428848, 2.37182379,
       2.37182379, 2.67472776, 3.3810882 , 3.32373429, 3.42184719,
       3.01285804, 2.72158094, 2.70428848, 2.58654217, 2.91180605,
       3.22701523, 3.18318961, 3.32373429, 2.73855525, 2.9347399 ,
       2.69257752, 3.00868837])

In [32]:
mpg_lambda

np.float64(-0.02122697750255029)

In [40]:
num_df = df[["mpg",	"cyl",	"disp",	"hp", "drat",	"wt", "qsec",	"vs",	"am",	"gear",	"carb"]]

In [ ]:
num_df = df.iloc[:, 1:]

In [42]:
normal_data = normalize(num_df, norm="l2")

In [43]:
df.loc[:, 1:] = normal_data

/var/folders/b2/02ycqbbj4nq9mtszv2phxc780000gn/T/ipykernel_19934/3101374250.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.03057764 0.03056964 0.02744987 0.02127089 0.02215921 0.02400902
 0.02217373 0.02662113 0.02601998 0.02859787 0.02860745 0.02887779
 0.02412014 0.02888136 0.01692802 0.01573846 0.01609207 0.04188695
 0.04759695 0.03834542 0.03230282 0.02269598 0.02353501 0.02280767
 0.01995263 0.04650254 0.02462332 0.03938015 0.01818695 0.04066314
 0.01773651 0.03040968]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, ["mpg",	"cyl",	"disp",	"hp", "drat",	"wt", "qsec",	"vs",	"am",	"gear",	"carb"]] = normal_data
/var/folders/b2/02ycqbbj4nq9mtszv2phxc780000gn/T/ipykernel_19934/3101374250.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.56059003 0.5604434  0.63820939 0.38996625 0.

In [44]:
df

car       mpg       cyl      disp        hp      drat  \
0             Mazda RX4  0.107022  0.030578  0.815404  0.560590  0.019875   
1         Mazda RX4 Wag  0.106994  0.030570  0.815190  0.560443  0.019870   
2            Datsun 710  0.156464  0.027450  0.741146  0.638209  0.026420   
3        Hornet 4 Drive  0.075866  0.021271  0.914648  0.389966  0.010919   
4     Hornet Sportabout  0.051797  0.022159  0.997164  0.000000  0.008725   
5               Valiant  0.072427  0.024009  0.900338  0.420158  0.011044   
6            Duster 360  0.039636  0.022174  0.997818  0.000000  0.008897   
7             Merc 240D  0.162389  0.026621  0.976330  0.000000  0.024558   
8              Merc 230  0.148314  0.026020  0.915903  0.000000  0.339040   
9              Merc 280  0.091513  0.028598  0.798834  0.586256  0.018684   
10            Merc 280C  0.084869  0.028607  0.799101  0.586453  0.018690   
11           Merc 450SE  0.059199  0.028878  0.995562  0.000000  0.011082   
12           Merc 450SL  0.052160  0.024120  0.831542  0.542703  0.087194   
13          Merc 450SLC  0.054875  0.028881  0.995685  0.000000  0.011083   
14   Cadillac Fleetwood  0.022006  0.016928  0.998753  0.000000  0.006200   
15  Lincoln Continental  0.020460  0.015738  0.904961  0.422971  0.005902   
16    Chrysler Imperial  0.029569  0.016092  0.885064  0.462647  0.006497   
17             Fiat 128  0.339284  0.041887  0.824126  0.000000  0.399706   
18          Honda Civic  0.361737  0.047597  0.900772  0.000000  0.058663   
19       Toyota Corolla  0.324977  0.038345  0.681590  0.623113  0.040454   
20        Toyota Corona  0.173628  0.032303  0.969892  0.000000  0.029880   
21     Dodge Challenger  0.043973  0.022696  0.902165  0.425550  0.007830   
22          AMC Javelin  0.044717  0.023535  0.894330  0.441281  0.009267   
23           Camaro Z28  0.037918  0.022808  0.997836  0.000000  0.010634   
24     Pontiac Firebird  0.047886  0.019953  0.997632  0.000000  0.007682   
25            Fiat X1-9  0.317380  0.046503  0.918425  0.000000  0.047433   
26        Porsche 914-2  0.160052  0.024623  0.740546  0.560181  0.315733   
27         Lotus Europa  0.299289  0.039380  0.936263  0.000000  0.037116   
28       Ford Pantera L  0.035919  0.018187  0.797952  0.600169  0.009594   
29         Ferrari Dino  0.133511  0.040663  0.982693  0.000000  0.024533   
30        Maserati Bora  0.033256  0.017737  0.667336  0.742716  0.007848   
31           Volvo 142E  0.162692  0.030410  0.919893  0.000000  0.323559   

          wt      qsec        vs        am      gear      carb  
0   0.013352  0.083885  0.000000  0.005096  0.020385  0.020385  
1   0.014648  0.086716  0.000000  0.005095  0.020380  0.020380  
2   0.015921  0.127711  0.006862  0.006862  0.027450  0.006862  
3   0.011398  0.068918  0.003545  0.000000  0.010635  0.003545  
4   0.009528 -0.047144  0.000000  0.000000  0.008310  0.005540  
5   0.013845  0.080910  0.004002  0.000000  0.012005  0.004002  
6   0.009895  0.043904  0.000000  0.000000  0.008315  0.011087  
7   0.021230 -0.133106  0.006655  0.000000  0.026621  0.013311  
8   0.020491  0.148964  0.006505  0.000000  0.026020  0.013010  
9   0.016396  0.087224  0.004766  0.000000  0.019065  0.019065  
10  0.016402 -0.090113  0.004768  0.000000  0.019072  0.019072  
11  0.014692  0.062809  0.000000  0.000000  0.010829  0.010829  
12  0.011246  0.053064  0.000000  0.000000  0.009045  0.009045  
13  0.013646 -0.064983  0.000000  0.000000  0.010831  0.010831  
14  0.011109  0.038046  0.000000  0.000000  0.006348  0.008464  
15  0.010671 -0.035057  0.000000  0.000000  0.005902  0.007869  
16  0.010752  0.035040  0.000000  0.000000  0.006035  0.008046  
17  0.023038 -0.203885  0.010472  0.010472  0.041887  0.010472  
18  0.019217  0.220374  0.011899  0.011899  0.047597  0.023798  
19  0.017591  0.190768  0.009586  0.009586  0.038345  0.009586  
20  0.019907  0.161595  0.008076  0.000000  0.024227  0.008076  
21  0.009986  0.047860  0.000000  0.000000  0.00